title: Stackbit Vanilla Theme
baseURL: /
params:
  header:
    title: Ocean Car Service
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: About
        url: /generic/
      - label: Bus
        url: /elements/
      - label: Contact
        url: /ipsum/
  footer:
    content: >-
      &copy; Ocean Car Service LLC. All rights reserved. Created by <a
      href="https://www.blazedlabs.com/" target="_blank">B</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=vanilla&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        new_window: true
  domain: 'https://oceancarservice-com-8245f.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
