title: Ocean Car Service
baseURL: /
params:
  favicon: 'https://blazed.sirv.com/RTM/logo/ocs.png'
  header:
    title: Ocean Car Service
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: About
        url: /about/
      - label: Contact
        url: /contact/
  footer:
    content: >-
      &copy; Ocean Car Service LLC. All rights reserved. Created by <a
      href="https://www.blazedlabs.com/" target="_blank">Blazed Labs</a>.
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://www.facebook.com/oceancarservicellc'
        new_window: true
      - label: GitHub
        url: 'https://github.com/blazed-labs/oceancarservice-com'
        new_window: true
      - label: RTM
        url: 'https://rtmtransit.com/'
        new_window: true
      - label: Drunk Bus
        url: 'https://drunkb.us/'
        new_window: false
        no_follow: false
        type: action
    links: []
  domain: 'https://oceancarservice-com.pages.dev'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
